import os
from dotenv import load_dotenv

load_dotenv()

ABUSEIPDB_API_KEY = os.getenv('ABUSEIPDB_API_KEY')
DISCORD_WEBHOOK_URL = os.getenv('DISCORD_WEBHOOK_URL')
SCAN_THRESHOLD = int(os.getenv('SCAN_THRESHOLD', '10'))
BRUTEFORCE_THRESHOLD = int(os.getenv('BRUTEFORCE_THRESHOLD', '5'))
CHECK_INTERVAL = int(os.getenv('CHECK_INTERVAL', '60'))
ABUSEIPDB_CHECK_ENABLED = os.getenv('ABUSEIPDB_CHECK_ENABLED', 'true').lower() == 'true'
EXTERNAL_IP_LIST_URL = os.getenv('EXTERNAL_IP_LIST_URL', '')
EXTERNAL_IP_LIST_KEY = os.getenv('EXTERNAL_IP_LIST_KEY', '')

DAILY_IP_LIMIT = 1000
SECONDS_PER_DAY = 86400
MIN_CHECK_INTERVAL = SECONDS_PER_DAY / DAILY_IP_LIMIT
